/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Entities.NhanVien;
import Entities.Person;
import Models.NhanVienModel;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class QuanLyNhanVienForm extends javax.swing.JFrame {

    public NhanVienModel nhanVienModel;
    public ArrayList<NhanVien> danhSachNhanVien;
    public DefaultTableModel tb_model;
    String fileName = "src\\main\\java\\files\\NhanVien.txt";

    /**
     * Creates new form QuanLyNhanVienForm
     */
    public QuanLyNhanVienForm() {
        initComponents();
        this.setTitle("Quản Lý Thông Tin Nhan Vien");
        this.setLocationRelativeTo(null);

        nhanVienModel = new NhanVienModel();
        nhanVienModel.fakeData();

        // Load data from file or use fake data if file is not available
        danhSachNhanVien = docfile(fileName);
        if (danhSachNhanVien == null || danhSachNhanVien.isEmpty()) {
            danhSachNhanVien = nhanVienModel.getDanhSachNhanVien();
        }

        tb_model = (DefaultTableModel) danhSachNhanVienTable.getModel();
        hienThiDanhSach(tb_model);
        chon_NhanVien();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        quanLyNhanVienLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        maNhanVienSearchLabel = new javax.swing.JLabel();
        maNhanVienSearch = new javax.swing.JTextField();
        timKiemButton = new javax.swing.JButton();
        themButton = new javax.swing.JButton();
        capNhatButton = new javax.swing.JButton();
        xoaButton = new javax.swing.JButton();
        ResetButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        danhSachNhanVienLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        danhSachNhanVienTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        thongTinNhanVienLabel = new javax.swing.JLabel();
        maNhanVienLabel = new javax.swing.JLabel();
        tenNhanVienLabel = new javax.swing.JLabel();
        soDienThoaiLabel = new javax.swing.JLabel();
        diaChiLabel = new javax.swing.JLabel();
        gioiTinhLabel = new javax.swing.JLabel();
        chucVuLabel = new javax.swing.JLabel();
        caLamViecLabel = new javax.swing.JLabel();
        luongLabel = new javax.swing.JLabel();
        thuongLabel = new javax.swing.JLabel();
        maNhanVienTextField = new javax.swing.JTextField();
        tenNhanVienTextField = new javax.swing.JTextField();
        soDienThoaiTextField = new javax.swing.JTextField();
        diaChiTextField = new javax.swing.JTextField();
        chucVuComboBox = new javax.swing.JComboBox<>();
        caLamViecComboBox = new javax.swing.JComboBox<>();
        luongTextField = new javax.swing.JTextField();
        thuongTextField = new javax.swing.JTextField();
        gioiTinhComboBox = new javax.swing.JComboBox<>();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        quanLyNhanVienLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        quanLyNhanVienLabel.setText("QUẢN LÝ THÔNG TIN NHÂN VIÊN");

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        maNhanVienSearchLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        maNhanVienSearchLabel.setText("Nhập mã nhân viên: ");

        maNhanVienSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        timKiemButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        timKiemButton.setText("Tìm Kiếm");
        timKiemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timKiemButtonActionPerformed(evt);
            }
        });

        themButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        themButton.setText("Thêm mới");
        themButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themButtonActionPerformed(evt);
            }
        });

        capNhatButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        capNhatButton.setText("Cập nhật");
        capNhatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capNhatButtonActionPerformed(evt);
            }
        });

        xoaButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        xoaButton.setText("Xóa");
        xoaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaButtonActionPerformed(evt);
            }
        });

        ResetButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ResetButton.setText("Reset");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(138, 138, 138)
                                                .addComponent(maNhanVienSearchLabel))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(70, 70, 70)
                                                .addComponent(themButton)
                                                .addGap(71, 71, 71)
                                                .addComponent(capNhatButton)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(maNhanVienSearch, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(40, 40, 40)
                                                .addComponent(timKiemButton)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(90, 90, 90)
                                                .addComponent(xoaButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        102, Short.MAX_VALUE)
                                                .addComponent(ResetButton)
                                                .addGap(84, 84, 84)))));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(maNhanVienSearchLabel)
                                        .addComponent(maNhanVienSearch, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(timKiemButton))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(themButton)
                                        .addComponent(capNhatButton)
                                        .addComponent(xoaButton)
                                        .addComponent(ResetButton))
                                .addContainerGap(27, Short.MAX_VALUE)));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        danhSachNhanVienLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        danhSachNhanVienLabel.setText("Danh sách nhân viên");

        danhSachNhanVienTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null, null, null }
                },
                new String[] {
                        "Mã nhân viên", "Tên nhân viên", "Số điện thoại", "Địa chỉ", "Giới tính", "Chức vụ",
                        "Ca làm việc", "Lương ", "Thưởng"
                }));
        jScrollPane1.setViewportView(danhSachNhanVienTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(288, 288, 288)
                                .addComponent(danhSachNhanVienLabel)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1)
                                .addContainerGap()));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(danhSachNhanVienLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(12, Short.MAX_VALUE)));

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        thongTinNhanVienLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        thongTinNhanVienLabel.setText("Thông tin nhân viên");

        maNhanVienLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        maNhanVienLabel.setText("Mã nhân viên");

        tenNhanVienLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tenNhanVienLabel.setText("Tên nhân viên");

        soDienThoaiLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        soDienThoaiLabel.setText("Số điện thoại");

        diaChiLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        diaChiLabel.setText("Địa chỉ");

        gioiTinhLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gioiTinhLabel.setText("Giới tính");

        chucVuLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chucVuLabel.setText("Chức vụ");

        caLamViecLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        caLamViecLabel.setText("Ca làm việc");

        luongLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        luongLabel.setText("Lương");

        thuongLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        thuongLabel.setText("Thưởng");

        maNhanVienTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tenNhanVienTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        soDienThoaiTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        diaChiTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        chucVuComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chucVuComboBox.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân viên thời vụ", "Nhân viên chính thức" }));

        caLamViecComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        caLamViecComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sáng", "Đêm" }));

        luongTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        thuongTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        gioiTinhComboBox.setEditable(true);
        gioiTinhComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gioiTinhComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap(107, Short.MAX_VALUE)
                                .addComponent(thongTinNhanVienLabel)
                                .addGap(88, 88, 88))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(maNhanVienLabel)
                                                .addComponent(tenNhanVienLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(soDienThoaiLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel3Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(chucVuLabel, javax.swing.GroupLayout.Alignment.LEADING,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(gioiTinhLabel, javax.swing.GroupLayout.Alignment.LEADING,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(diaChiLabel, javax.swing.GroupLayout.Alignment.LEADING,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(caLamViecLabel)
                                        .addComponent(luongLabel)
                                        .addComponent(thuongLabel))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel3Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(maNhanVienTextField)
                                        .addComponent(tenNhanVienTextField)
                                        .addComponent(soDienThoaiTextField)
                                        .addComponent(diaChiTextField)
                                        .addComponent(chucVuComboBox, 0, 1, Short.MAX_VALUE)
                                        .addComponent(caLamViecComboBox, 0, 165, Short.MAX_VALUE)
                                        .addComponent(luongTextField)
                                        .addComponent(thuongTextField)
                                        .addComponent(gioiTinhComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(thongTinNhanVienLabel)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(maNhanVienLabel)
                                        .addComponent(maNhanVienTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tenNhanVienLabel)
                                        .addComponent(tenNhanVienTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(soDienThoaiLabel)
                                        .addComponent(soDienThoaiTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(diaChiLabel)
                                        .addComponent(diaChiTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(gioiTinhLabel)
                                        .addComponent(gioiTinhComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(chucVuLabel)
                                        .addComponent(chucVuComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(caLamViecLabel)
                                        .addComponent(caLamViecComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(luongLabel)
                                        .addComponent(luongTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(thuongLabel)
                                        .addComponent(thuongTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(49, Short.MAX_VALUE)));

        backButton.setText("Trở lại");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                layout.createSequentialGroup()
                                                        .addGap(0, 228, Short.MAX_VALUE)
                                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(174, 174, 174))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addComponent(backButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(quanLyNhanVienLabel)
                                                .addGap(366, 366, 366)))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(quanLyNhanVienLabel))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(backButton)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chon_NhanVien() {
        try {
            // Thêm vào sau khi đã tạo bảng danhSachXeTable
            danhSachNhanVienTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent event) {
                    int selectedRow = danhSachNhanVienTable.getSelectedRow();
                    if (selectedRow >= 0) {
                        maNhanVienTextField.setText(danhSachNhanVienTable.getValueAt(selectedRow, 0).toString());
                        maNhanVienTextField.setEnabled(false);
                        tenNhanVienTextField.setText(danhSachNhanVienTable.getValueAt(selectedRow, 1).toString());
                        soDienThoaiTextField.setText(danhSachNhanVienTable.getValueAt(selectedRow, 2).toString());

                        // Đặt giá trị được chọn cho JComboBox
                        gioiTinhComboBox.setSelectedItem(danhSachNhanVienTable.getValueAt(selectedRow, 4).toString());
                        chucVuComboBox.setSelectedItem(danhSachNhanVienTable.getValueAt(selectedRow, 5).toString());
                        caLamViecComboBox.setSelectedItem(danhSachNhanVienTable.getValueAt(selectedRow, 6).toString());

                        luongTextField.setText(danhSachNhanVienTable.getValueAt(selectedRow, 7).toString());
                        thuongTextField.setText(danhSachNhanVienTable.getValueAt(selectedRow, 8).toString());

                        diaChiTextField.setText(danhSachNhanVienTable.getValueAt(selectedRow, 3).toString());
                    }
                }
            });
        } catch (Exception e) {
            System.out.println("Loi" + e.getMessage());
        }
    }

    private void themButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_themButtonActionPerformed
        try {
            if (maNhanVienTextField.getText().isEmpty() || tenNhanVienTextField.getText().isEmpty() ||
                    soDienThoaiTextField.getText().isEmpty() || diaChiTextField.getText().isEmpty() ||
                    luongTextField.getText().isEmpty() || thuongTextField.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Bạn cần nhập đầy đủ thông tin", "Thông báo",
                        JOptionPane.WARNING_MESSAGE);
            } else {
                this.maNhanVienTextField.setEnabled(true);

                String maNhanVien = maNhanVienTextField.getText();
                if (kiemTraMaNhanVien(maNhanVien)) {
                    JOptionPane.showMessageDialog(rootPane, "Mã nhân viên đã tồn tại", "Thông báo",
                            JOptionPane.WARNING_MESSAGE);
                } else {
                    String tenNhanVien = tenNhanVienTextField.getText();
                    String soDienThoai = soDienThoaiTextField.getText();
                    String diaChi = diaChiTextField.getText();
                    long luong = Long.parseLong(luongTextField.getText());
                    long thuong = Long.parseLong(thuongTextField.getText());
                    String chucVu = chucVuComboBox.getSelectedItem() + "";
                    String caLamViec = caLamViecComboBox.getSelectedItem() + "";
                    String gioiTinh = gioiTinhComboBox.getSelectedItem() + "";
                    // Khởi tạo đối tượng NhanVien
                    NhanVien newNhanVien = new NhanVien(chucVu, luong, caLamViec, thuong, maNhanVien, tenNhanVien,
                            soDienThoai, diaChi, gioiTinh);

                    // Thêm nhân viên mới vào danh sách
                    danhSachNhanVien.add(newNhanVien);
                    JOptionPane.showMessageDialog(rootPane, "Thêm nhân viên thành công!", "Thông báo",
                            JOptionPane.INFORMATION_MESSAGE);
                    LuuFile(fileName, danhSachNhanVien);
                    hienThiDanhSach(tb_model);
                }
            }
        } catch (Exception e) {
            System.out.println("Lỗi: " + e.getMessage());
        }
    }// GEN-LAST:event_themButtonActionPerformed

    private void capNhatButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_capNhatButtonActionPerformed
        try {
            if (maNhanVienTextField.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Bạn cần nhập mã nhân viên để tìm kiếm", "Thông báo",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                String maNVSearch = maNhanVienTextField.getText();
                NhanVien nhanVien = timKiemNhanVien(maNVSearch);
                if (nhanVien != null) {
                    maNhanVienTextField.setEnabled(false);
                    maNhanVienTextField.setText(nhanVien.getId());
                    String tenNhanVienMoi = tenNhanVienTextField.getText();
                    String soDienThoaiMoi = soDienThoaiTextField.getText();
                    String diaChiMoi = diaChiTextField.getText();
                    String gioiTinhMoi = gioiTinhComboBox.getSelectedItem() + "";
                    String chucVuMoi = chucVuComboBox.getSelectedItem() + "";
                    String caLamViecMoi = caLamViecComboBox.getSelectedItem() + "";
                    long luongMoi = Long.parseLong(luongTextField.getText());
                    long thuongMoi = Long.parseLong(thuongTextField.getText());

                    nhanVien.setTen(tenNhanVienMoi);
                    nhanVien.setSoDienThoai(soDienThoaiMoi);
                    nhanVien.setDiaChi(diaChiMoi);
                    nhanVien.setGioiTinh(gioiTinhMoi);
                    nhanVien.setChucVu(chucVuMoi);
                    nhanVien.setCaLamViec(caLamViecMoi);
                    nhanVien.setLuong(luongMoi);
                    nhanVien.setThuong(thuongMoi);

                    // Cập nhật dữ liệu trên bảng
                    int rowIndex = timIndexNhanVienTrongBang(maNVSearch);
                    if (rowIndex != -1) {
                        danhSachNhanVienTable.getModel().setValueAt(tenNhanVienMoi, rowIndex, 1);
                        danhSachNhanVienTable.getModel().setValueAt(soDienThoaiMoi, rowIndex, 2);
                        danhSachNhanVienTable.getModel().setValueAt(diaChiMoi, rowIndex, 3);
                        danhSachNhanVienTable.getModel().setValueAt(gioiTinhMoi, rowIndex, 4);
                        danhSachNhanVienTable.getModel().setValueAt(chucVuMoi, rowIndex, 5);
                        danhSachNhanVienTable.getModel().setValueAt(caLamViecMoi, rowIndex, 6);
                        danhSachNhanVienTable.getModel().setValueAt(luongMoi, rowIndex, 7);
                        danhSachNhanVienTable.getModel().setValueAt(thuongMoi, rowIndex, 8);
                    }
                    LuuFile(fileName, danhSachNhanVien);
                    JOptionPane.showMessageDialog(rootPane, "Đã cập nhật thành công", "Thông báo",
                            JOptionPane.INFORMATION_MESSAGE);

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Không tìm thấy mã nhân viên", "Thông báo",
                            JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }// GEN-LAST:event_capNhatButtonActionPerformed

    private void timKiemButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_timKiemButtonActionPerformed
        try {
            if (maNhanVienSearch.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Bạn cần nhập mã nhân viên để tìm kiếm", "Thông báo",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                String maNhanVien = maNhanVienSearch.getText();
                NhanVien nhanVien = timKiemNhanVien(maNhanVien);
                if (nhanVien != null) {
                    tenNhanVienLabel.setText(nhanVien.getTen());
                    maNhanVienTextField.setEnabled(false);
                    maNhanVienTextField.setText(nhanVien.getId());
                    soDienThoaiTextField.setText(nhanVien.getSoDienThoai());
                    diaChiTextField.setText(nhanVien.getDiaChi());
                    gioiTinhComboBox.setSelectedItem(nhanVien.getGioiTinh());
                    chucVuComboBox.setSelectedItem(nhanVien.getChucVu());
                    caLamViecComboBox.setSelectedItem(nhanVien.getCaLamViec());
                    luongTextField.setText(nhanVien.getLuong() + "");
                    thuongTextField.setText(nhanVien.getThuong() + "");

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Không tìm thấy mã nhân viên", "Thông báo",
                            JOptionPane.INFORMATION_MESSAGE);
                    tenNhanVienLabel.setText("");
                    maNhanVienTextField.setText("");
                    soDienThoaiTextField.setText("");
                    diaChiTextField.setText("");
                    luongTextField.setText("");
                    thuongTextField.setText("");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }// GEN-LAST:event_timKiemButtonActionPerformed

    private void xoaButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_xoaButtonActionPerformed
        try {
            if (maNhanVienTextField.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Bạn cần nhập mã nhân viên hoặc tìm kiếm mã nhân viên cần xóa",
                        "Thông báo", HEIGHT);
            } else {
                String maNhanVien = maNhanVienTextField.getText();
                NhanVien nhanVien = timKiemNhanVien(maNhanVien);
                if (nhanVien != null) {
                    danhSachNhanVien.remove(nhanVien);
                    LuuFile(fileName, danhSachNhanVien);
                    int rowIndex = timIndexNhanVienTrongBang(maNhanVien);
                    if (rowIndex != -1) {
                        // Xóa hàng từ bảng
                        DefaultTableModel model = (DefaultTableModel) danhSachNhanVienTable.getModel();
                        model.removeRow(rowIndex);
                    }

                    JOptionPane.showMessageDialog(rootPane, "Xóa thành công", "Thông báo", HEIGHT);

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Không tìm thấy nhân viên để xóa", "Thông báo",
                            JOptionPane.WARNING_MESSAGE);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Đã xảy ra lỗi: " + e.getMessage(), "Lỗi",
                    JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_xoaButtonActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ResetButtonActionPerformed
        tenNhanVienTextField.setText("");
        maNhanVienTextField.setText("");
        soDienThoaiTextField.setText("");
        diaChiTextField.setText("");
        luongTextField.setText("");
        thuongTextField.setText("");
    }// GEN-LAST:event_ResetButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_backButtonActionPerformed
        this.dispose();
        // Mở JFrame của trang chủ
        TrangChuForm trangChu = new TrangChuForm();
        trangChu.setVisible(true);
    }// GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVienForm.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVienForm.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVienForm.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVienForm.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyNhanVienForm().setVisible(true);
            }
        });
    }

    // luu File vào tệp
    public void LuuFile(String fileName, ArrayList<NhanVien> danhSachNhanVien) {
        // Tạo luồng ghi file
        try {
            FileOutputStream fs = new FileOutputStream(fileName);
            // Tạo luồng để serial đối tượng
            ObjectOutputStream os = new ObjectOutputStream(fs);
            // chuyển tải đối tượng tới đích (tập tin)
            os.writeObject(danhSachNhanVien);
            // đóng luồng

            os.close();
            fs.close();
            // db.LuuFile(fileName, dsSV);
            System.out.println("Lưu file thành công");
        } catch (IOException ex) {
            System.out.println("loi" + ex.getMessage());
        }
    }

    // doc file ra
    public ArrayList docfile(String filename) {

        danhSachNhanVien = new ArrayList<>();
        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream(filename))) {
            danhSachNhanVien = (ArrayList<NhanVien>) ois.readObject();

        } catch (IOException E) {
            System.out.println("Loi" + E.getMessage());
        } catch (Exception ex) {
            System.out.println("Loi" + ex.getMessage());
        }
        return danhSachNhanVien;
    }

    // hiển thị danh sach fakedata
    public void hienThiDanhSach(DefaultTableModel model) {
        model.setRowCount(0);
        for (NhanVien nhanVien : danhSachNhanVien) {
            model.addRow(new Object[] {
                    nhanVien.getId(),
                    nhanVien.getTen(),
                    nhanVien.getSoDienThoai(),
                    nhanVien.getDiaChi(),
                    nhanVien.getGioiTinh(),
                    nhanVien.getChucVu(),
                    nhanVien.getCaLamViec(),
                    nhanVien.getLuong(),
                    nhanVien.getThuong(),
            });
        }
    }

    private boolean kiemTraMaNhanVien(String maNhanVien) {
        for (NhanVien nv : danhSachNhanVien) {
            if (nv.getId().equals(maNhanVien)) {
                return true;
            }
        }
        return false;
    }

    private NhanVien timKiemNhanVien(String id) {
        for (NhanVien nv : danhSachNhanVien) {
            if (nv.getId().equals(id)) {
                return nv;
            }
        }
        return null;
    }

    private int timIndexNhanVienTrongBang(String maNhanVienSearch) {
        DefaultTableModel model = (DefaultTableModel) danhSachNhanVienTable.getModel();
        int rowCount = model.getRowCount();
        for (int i = 0; i < rowCount; i++) {
            String maNhanVien = model.getValueAt(i, 0).toString();
            if (maNhanVien.equals(maNhanVienSearch)) {
                return i; // Trả về vị trí hàng nếu mã xe được tìm thấy
            }
        }
        return -1; // Trả về -1 nếu không tìm thấy mã xe trong bảng
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ResetButton;
    private javax.swing.JButton backButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> caLamViecComboBox;
    private javax.swing.JLabel caLamViecLabel;
    private javax.swing.JButton capNhatButton;
    private javax.swing.JComboBox<String> chucVuComboBox;
    private javax.swing.JLabel chucVuLabel;
    private javax.swing.JLabel danhSachNhanVienLabel;
    private javax.swing.JTable danhSachNhanVienTable;
    private javax.swing.JLabel diaChiLabel;
    private javax.swing.JTextField diaChiTextField;
    private javax.swing.JComboBox<String> gioiTinhComboBox;
    private javax.swing.JLabel gioiTinhLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel luongLabel;
    private javax.swing.JTextField luongTextField;
    private javax.swing.JLabel maNhanVienLabel;
    private javax.swing.JTextField maNhanVienSearch;
    private javax.swing.JLabel maNhanVienSearchLabel;
    private javax.swing.JTextField maNhanVienTextField;
    private javax.swing.JLabel quanLyNhanVienLabel;
    private javax.swing.JLabel soDienThoaiLabel;
    private javax.swing.JTextField soDienThoaiTextField;
    private javax.swing.JLabel tenNhanVienLabel;
    private javax.swing.JTextField tenNhanVienTextField;
    private javax.swing.JButton themButton;
    private javax.swing.JLabel thongTinNhanVienLabel;
    private javax.swing.JLabel thuongLabel;
    private javax.swing.JTextField thuongTextField;
    private javax.swing.JButton timKiemButton;
    private javax.swing.JButton xoaButton;
    // End of variables declaration//GEN-END:variables
}
